### PR TITLE
Add "cs" basis as a possibility for smooth.construct.cb.smooth.spec

### PR DESCRIPTION
**Pull request by Aariq**
All I did in this PR is edit an `if` statement that allows `"cs"` to be a basis for a crossbasis smooth created by `mgcv::s()`.  I think this "just works" because all that `smooth.construct.cs.smooth.spec()` does is add an attribute to `object`, and then pass it to `smooth.construct.cr.smooth.spec()`.

To see that this is working:

``` r
library(dlnm)
#> This is dlnm 2.4.2. For details: help(dlnm) and vignette('dlnmOverview').
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-33. For overview type 'help("mgcv-package")'.

Q <- as.matrix(nested[, 5:14]) 
L <- matrix(1:ncol(Q), nrow = nrow(Q), ncol = ncol(Q), byrow = TRUE)

m_cr <- gam(case ~ age + s(Q, L, bs = "cb", xt = list(bs = "cr")), family = binomial, data = nested)
m_cs <- gam(case ~ age + s(Q, L, bs = "cb", xt = list(bs = "cs")), family = binomial, data = nested)
#increased gamma exaggerates the difference between "cr" and "cs"

cr_pred <- crosspred("Q", m_cr)
#> centering value unspecified. Automatically set to 600
cs_pred <- crosspred("Q", m_cs)
#> centering value unspecified. Automatically set to 600

#cs spline is pulled toward 0 in both lag and response dimensions

plot(cr_pred, ptype = "slices", lag = 10, ylim = c(-50, 50))
```

``` r
plot(cs_pred, ptype = "slices", lag = 10, ylim = c(-50, 50))
```

``` r

plot(cr_pred, ptype = "slices", var = 1000, ylim = c(-20, 40))
```

``` r
plot(cs_pred, ptype = "slices", var = 1000, ylim = c(-20, 40))
```

<sup>Created on 2020-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I also added an example to the help file for `smooth.construct.cb.smooth.spec()` and updated NEWS.md. 

I can't get the vignettes to build locally, so wasn't able to run R CMD check

### CODE REVIEW

**Comment by Aariq** [comment]
Forgot to mention: this closes #5

**Comment by gasparrini** [comment]
Thanks, Eric.

I would like to see some more checks, for example used in some of the case-studies and/or simulations in https://github.com/gasparrini/2017_gasparrini_Biomet_Rcodedata.

In particular, I would check if the definition of the penalty matrices (smooth.construct.cb.smooth.spec) and predictions (see Predict.matrix.cb.smooth) work as expected.

Antonio Gasparrini, BSc Mbiol MSc PhD
-------------------------------
Professor of Biostatistics and Epidemiology
London School of Hygiene & Tropical Medicine
15-17 Tavistock Place, London WC1H 9SH, UK
Office: 0044 (0)20 79272406
Mobile: 0044 (0)79 64925523
Skype: a.gasparrini
Twitter: @AGasparrini75
http://www.ag-myresearch.com

**Comment by Aariq** [comment]
That makes sense.  I haven't checked how this change interacts with `predict()`.  I'll add some tests and let you know how it goes.

**Comment by Aariq** [comment]
I have a question: what is the intended difference (if any) between the following two ways of specifying marginal basis?

1)
```
gam(y ~ s(Q, L, bs = "cb", xt = list(bs = c("ps", "cr"))))
```
2)
```
gam(y ~ s(Q, L, bs = "cb", xt = list(argvar = list(fun = "ps"), arglag = list(fun = "cr"))))) 
```

Method 1 is what is described in the help file for `smooth.construct.cb.smooth.spec`, but I see that method 2 is what is used in the 2017 paper.  They seem to be handled differently by `smooth.construct.cb.smooth.spec`.

**Comment by Aariq** [comment]
I'm not totally convinced that this is working right as the difference between "cr" and "cs" in a cross basis seems way more drastic than in a normal 1D spline where I see only minor differences.  I'm also no longer convinced that I ever want to use the "cs" basis personally, so I'm going to close this pull request.

**Comment by gasparrini** [comment]
I’ve always had doubts that this could work so easily.
In addition, shrinking to null this bidimensional shape in one dimension causes the other dimension to shrink as well, which seems problematic.

In any case, thanks for the interest and for doing some work on the topic.
Maybe it will turn out useful in the future.

Best

Antonio Gasparrini, BSc Mbiol MSc PhD
-------------------------------
Professor of Biostatistics and Epidemiology
London School of Hygiene & Tropical Medicine
15-17 Tavistock Place, London WC1H 9SH, UK
Office: 0044 (0)20 79272406
Mobile: 0044 (0)79 64925523
Skype: a.gasparrini
Twitter: @AGasparrini75
http://www.ag-myresearch.com

**Pull request closed without merging**
